import os
from glob import glob

from setuptools import find_packages, setup

package_name = 'lrs_halmstad'

setup(
    name=package_name,
    version='0.0.0',
    packages=find_packages(exclude=['test']),
    py_modules=['lap'],
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        (os.path.join('share', package_name), glob('launch/*.launch.py')),
        (os.path.join('share', package_name, 'config'), glob('config/*.yaml') + glob('config/*.config')),
        (os.path.join('share', package_name, 'config', 'baylands_waypoints'), glob('config/baylands_waypoints/*.yaml')),
        (os.path.join('share', package_name, 'config', 'trackers'), glob('config/trackers/*.yaml')),
        (os.path.join('share', package_name, 'worlds'), glob('worlds/*.sdf')),
        (os.path.join('share', package_name, 'hook'), glob('hook/*.dsv')),
        ('share/' + "/matrice_100/materials/textures", glob('models/matrice_100/materials/textures/*')),        
        ('share/' + "/matrice_100/meshes", glob('models/matrice_100/meshes/*')),        
        ('share/' + "/zenmuse_z3/materials/textures", glob('models/zenmuse_z3/materials/textures/*')),        
        ('share/' + "/zenmuse_z3/meshes", glob('models/zenmuse_z3/meshes/*')),        
        ('share/' + package_name, ['package.xml']),
        ('share/' + package_name + "/urdf", glob('urdf/*.xacro')),                  ('share/' + package_name + "/xacro", glob('xacro/*.xacro')),                ('share/' + package_name + "/sdf", glob('sdf/*.sdf')),              
        ('share/' + package_name + "/models/piraya/materials/textures", glob('models/piraya/materials/textures/*')),
        ('share/' + package_name + "/models/piraya/meshes", glob('models/piraya/meshes/*')),                
        ('share/' + package_name + "/models/person_standing_static", glob('models/human/person_standing_static/model.*')),        
        ('share/' + package_name + "/models/person_standing_static/materials/textures", glob('models/human/person_standing_static/materials/textures/*')),
        ('share/' + package_name + "/models/person_standing_static/meshes", glob('models/human/person_standing_static/meshes/*')),                
        ('share/' + package_name + "/models/person_standing", glob('models/people/person_standing/model.*')),        
        ('share/' + package_name + "/models/person_standing/materials/textures", glob('models/people/person_standing/materials/textures/*')),
        ('share/' + package_name + "/models/person_standing/meshes", glob('models/people/person_standing/meshes/*')),                
        ('share/' + package_name + "/models/person_walking", glob('models/people/person_walking/model.*')),        
        ('share/' + package_name + "/models/person_walking/materials/textures", glob('models/people/person_walking/materials/textures/*')),
        ('share/' + package_name + "/models/person_walking/meshes", glob('models/people/person_walking/meshes/*')),                
        ('share/' + package_name + "/models/bobeye", glob('models/people/bobeye/model.*')),        
        ('share/' + package_name + "/models/bobeye/meshes", glob('models/people/bobeye/meshes/*')),                
        ('share/' + package_name + "/models/gertrudiseye", glob('models/people/gertrudiseye/model.*')),        
        ('share/' + package_name + "/models/gertrudiseye/meshes", glob('models/people/gertrudiseye/meshes/*')),                
        ('share/' + package_name + "/models/kumaeye", glob('models/people/kumaeye/model.*')),        
        ('share/' + package_name + "/models/kumaeye/meshes", glob('models/people/kumaeye/meshes/*')),                
        ('share/' + package_name + "/models/naokoeye", glob('models/people/naokoeye/model.*')),        
        ('share/' + package_name + "/models/naokoeye/meshes", glob('models/people/naokoeye/meshes/*')),                
        ('share/' + package_name + "/models/oliveeye", glob('models/people/oliveeye/model.*')),        
        ('share/' + package_name + "/models/oliveeye/meshes", glob('models/people/oliveeye/meshes/*')),                
        ('share/' + package_name + "/models/timmyeye", glob('models/people/timmyeye/model.*')),        
        ('share/' + package_name + "/models/timmyeye/meshes", glob('models/people/timmyeye/meshes/*')),                
        ('share/' + package_name + "/models/medkit", glob('models/medkit/model.*')),        
        ('share/' + package_name + "/models/medkit/materials/textures", glob('models/medkit/materials/textures/*')),
        ('share/' + package_name + "/models/medkit/meshes", glob('models/medkit/meshes/*')),
        
        ('share/' + package_name + "/models/miniusv/materials", glob('models/miniusv/materials/*')),
        ('share/' + package_name + "/models/miniusv/meshes", glob('models/miniusv/meshes/*')),                
        ('share/' + package_name + "/models/suv/materials/textures", glob('models/suv/materials/textures/*')),
        ('share/' + package_name + "/models/suv/meshes", glob('models/suv/meshes/*')),                
        ('share/' + package_name + "/models/hatchback/materials/textures", glob('models/hatchback/materials/textures/*')),
        ('share/' + package_name + "/models/hatchback/meshes", glob('models/hatchback/meshes/*')),                
        ('share/' + package_name + "/models/fire_truck/materials/textures", glob('models/fire_truck/materials/textures/*')),
        ('share/' + package_name + "/models/fire_truck/meshes", glob('models/fire_truck/meshes/*')),
        ('share/' + package_name + "/models/mahas_farm_aug23_8M_24", glob('models/mahas_farm_aug23_8M_24/model*')),
        ('share/' + package_name + "/models/mahas_farm_aug23_8M_24/meshes", glob('models/mahas_farm_aug23_8M_24/meshes/*')),
        ('share/' + package_name + "/models/mahas_farm_aug23_8M_24/materials/textures", glob('models/mahas_farm_aug23_8M_24/materials/textures/*')),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='tompe',
    maintainer_email='tommy.persson@liu.se',
    description='TODO: Package description',
    license='TODO: License declaration',
    extras_require={
        'test': [
            'pytest',
        ],
    },
    entry_points={
        'console_scripts': [
            'generate_sdf = lrs_halmstad.generate_sdf:main',            
            'command = lrs_halmstad.command:main',            
            'contract_check = lrs_halmstad.contract_check:main',
            'camera_tracker = lrs_halmstad.follow.camera_tracker:main',
            'follow_uav = lrs_halmstad.follow.follow_uav:main',
            'follow_uav_odom = lrs_halmstad.follow.follow_uav_odom:main',
            'visual_follow_controller = lrs_halmstad.follow.visual_follow_controller:main',
            'visual_actuation_bridge = lrs_halmstad.follow.visual_actuation_bridge:main',
            'follow_point_generator = lrs_halmstad.follow.follow_point_generator:main',
            'follow_point_planner = lrs_halmstad.follow.follow_point_planner:main',
            'selected_target_filter = lrs_halmstad.follow.selected_target_filter:main',
            'visual_target_estimator = lrs_halmstad.perception.visual_target_estimator:main',
            "export_yolo_onnx = lrs_halmstad.perception.export_yolo_onnx:main",
            "leader_detector = lrs_halmstad.perception.leader_detector:main",
            "leader_tracker = lrs_halmstad.perception.leader_tracker:main",
            "support_detection_mux = lrs_halmstad.perception.support_detection_mux:main",
            "dji0_to_ugv_forwarder = lrs_halmstad.perception.dji0_to_ugv_forwarder:main",
            "leader_estimator = lrs_halmstad.perception.leader_estimator:main",
            "gazebo_pose_tcp_bridge = lrs_halmstad.sim.gazebo_pose_tcp_bridge:main",
            "gazebo_model_pose_bridge = lrs_halmstad.sim.gazebo_model_pose_bridge:main",
            "omnet_metrics_bridge = lrs_halmstad.sim.omnet_metrics_bridge:main",
            "pose_cmd_to_odom = lrs_halmstad.sim.pose_cmd_to_odom:main",
            "pose_cov_to_odom = lrs_halmstad.sim.pose_cov_to_odom:main",
            "odom_to_tf = lrs_halmstad.sim.odom_to_tf:main",
            "controller = lrs_halmstad.sim.controller:main",
            "simulator = lrs_halmstad.sim.simulator:main",
            "clock_guard = lrs_halmstad.sim.clock_guard:main",
            "latest_scan_relay = lrs_halmstad.sim.latest_scan_relay:main",
            "sim_dataset_capture = lrs_halmstad.dataset.sim_dataset_capture:main",
            "run_follow_control = lrs_halmstad.tools.follow_control:main",
            "support_camera_scanner = lrs_halmstad.tools.support_camera_scanner:main",
            "collect_leader_dataset = lrs_halmstad.tools.collect_leader_dataset:main",
            "run_uav_command_logger = lrs_halmstad.tools.uav_command_logger:main",
            "run_dataset_make_obb = lrs_halmstad.dataset.make_obb:main",
            "run_dataset_prune_negatives = lrs_halmstad.dataset.prune_negatives:main",
            "run_dataset_sync_check = lrs_halmstad.dataset.sync_check:main",
            "run_perception_benchmark_summary = lrs_halmstad.tools.perception_benchmark_summary:main",
            "ugv_nav2_driver = lrs_halmstad.nav.ugv_nav2_driver:main",
            "ugv_nav2_goal_tester = lrs_halmstad.nav.ugv_nav2_goal_tester:main",
              # optional later:
              # 'metrics_node = lrs_halmstad.metrics_node:main',
        ],
    },
)
